-- MySQL Script generated by MySQL Workbench
-- Thu Feb 12 12:13:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpeedyBreak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpeedyBreak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpeedyBreak` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema e_commerce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_commerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_commerce_db` ;
USE `SpeedyBreak` ;

-- -----------------------------------------------------
-- Table `SpeedyBreak`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpeedyBreak`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpeedyBreak`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpeedyBreak`.`categoria` (
  `id_categoria` INT NOT NULL,
  `descrizione` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;

USE `e_commerce_db` ;

-- -----------------------------------------------------
-- Table `e_commerce_db`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`utente` (
  `id_utente` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cognome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `ruolo` VARCHAR(50) NULL DEFAULT 'customer',
  PRIMARY KEY (`id_utente`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `e_commerce_db`.`prodotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`prodotto` (
  `id_prodotto` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `descrizione` TEXT NULL DEFAULT NULL,
  `prezzo` DECIMAL(10,2) NOT NULL,
  `giacenza` TINYINT NULL DEFAULT TRUE,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_prodotto`),
  INDEX `fk_prodotto_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_prodotto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `SpeedyBreak`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `e_commerce_db`.`ordine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`ordine` (
  `id_ordine` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `data_ordine` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `stato` VARCHAR(50) NULL DEFAULT NULL,
  `metodo` VARCHAR(50) NULL DEFAULT NULL,
  `id_utente` INT NOT NULL,
  `nota` MEDIUMTEXT NULL,
  `data_ritiro` DATETIME NULL,
  PRIMARY KEY (`id_ordine`),
  INDEX (`id_utente` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_utente`)
    REFERENCES `e_commerce_db`.`utente` (`id_utente`));


-- -----------------------------------------------------
-- Table `e_commerce_db`.`DETTAGLIO_ORDINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_db`.`DETTAGLIO_ORDINE` (
  `id_ordine` INT NULL DEFAULT NULL,
  `id_prodotto` INT NULL DEFAULT NULL,
  `quantità` INT NULL DEFAULT 1,
  PRIMARY KEY (`id_ordine`, `id_prodotto`),
  INDEX (`id_prodotto` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_ordine`)
    REFERENCES `e_commerce_db`.`ordine` (`id_ordine`),
  CONSTRAINT ``
    FOREIGN KEY (`id_prodotto`)
    REFERENCES `e_commerce_db`.`prodotto` (`id_prodotto`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
